services:

# сервер конфигурации
  configSrv1:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: configSrv1 
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config1-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv2:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: configSrv2
    restart: always
    ports:
      - "27018:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    volumes:
      - config2-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      
  configSrv3:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: configSrv3
    restart: always
    ports:
      - "27019:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    volumes:
      - config3-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 1-й шард
  shard1a:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1a
    restart: always
    ports:
      - "27016:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    volumes:
      - shard1a-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 1-й шард
  shard1b:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1b
    restart: always
    ports:
      - "27021:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.21
    volumes:
      - shard1b-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 1-й шард
  shard1c:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1c
    restart: always
    ports:
      - "27022:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.22
    volumes:
      - shard1c-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 2-й шард 
  shard2a:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2a
    restart: always
    ports:
      - "27023:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.30
    volumes:
      - shard2a-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard2", # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 2-й шард 
  shard2b:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2b
    restart: always
    ports:
      - "27024:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.31
    volumes:
      - shard2b-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard2", # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

# 2-й шард 
  shard2c:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2c
    restart: always
    ports:
      - "27025:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.32
    volumes:
      - shard2c-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "shard2", # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  # роутер
  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos", # обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017", # передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      - configSrv1
      - configSrv2
      - configSrv3
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
    networks:
      - app-network
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  config1-data:
  config2-data:
  config3-data:
  shard1a-data:
  shard1b-data:
  shard1c-data:
  shard2a-data:
  shard2b-data:
  shard2c-data:


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
